### ISSUE TITLE
Symlinked assets dir not working, allow dotenv var for assets path?

### ISSUE THREAD

**Issue by dizzystuff** [axllent/ssbak#4]
Hi! Thanks so much for this module. 

We keep our assets directory (and dotenv) outside of the release directory, and symlink them in during a deployment. We're very keen to run ssbak at the start of our deploy script, in order to provide a reversion mechanism if something goes wrong mid-deploy or if the dev/build borks when the deploy script runs towards its end.

However I'm getting an error when running `ssbak save` which I believe is due to the symlink - if I put the actual assets dir inside /public and rerun ssbak, it works perfectly.

```
Compressing '..../releases/20220203130000/public/assets' (22 B) to '/tmp/ssbak-43659d4d7626/assets.tar.gz'
panic: runtime error: slice bounds out of range [62:45]

goroutine 1 [running]:
github.com/axllent/ssbak/utils.writeDirectory(0xc00019e190, 0x45, 0xc0001e8000, 0xc00019e190, 0x3e, 0x0, 0x0)
	/mnt/apache/sandpit/go/ssbak/utils/targz.go:205 +0x525
github.com/axllent/ssbak/utils.compress(0xc00019e190, 0x45, 0xc0001c8090, 0x25, 0xc00019e190, 0x3e, 0x0, 0x0)
	/mnt/apache/sandpit/go/ssbak/utils/targz.go:162 +0x239
github.com/axllent/ssbak/utils.TarGZCompress(0xc00019e190, 0x45, 0xc0001c8090, 0x25, 0x0, 0x0)
	/mnt/apache/sandpit/go/ssbak/utils/targz.go:39 +0x1d3
github.com/axllent/ssbak/utils.AssetsToTarGz(0xc00019e190, 0x45, 0xc0001c8090, 0x25, 0x3, 0xc0001d8000)
	/mnt/apache/sandpit/go/ssbak/utils/assets.go:27 +0x2be
github.com/axllent/ssbak/cmd.glob..func6(0xa81e80, 0xc00006a240, 0x2, 0x3, 0x0, 0x0)
	/mnt/apache/sandpit/go/ssbak/cmd/save.go:57 +0x357
github.com/spf13/cobra.(*Command).execute(0xa81e80, 0xc00006a210, 0x3, 0x3, 0xa81e80, 0xc00006a210)
	/home/ralph/.cache/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xa81be0, 0x6, 0x0, 0x0)
	/home/ralph/.cache/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/ralph/.cache/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/axllent/ssbak/cmd.Execute()
	/mnt/apache/sandpit/go/ssbak/cmd/root.go:39 +0x6b
main.main()
	/mnt/apache/sandpit/go/ssbak/main.go:26 +0x25
```

If allowing ssbak to follow/use the symlink is an easy change, it'd be great if possible.

If it's not, then alternatively would it be possible to allow a path to the assets directory to be set in the dotenv file, as we do with the database name (for example)? Maintaining backwards compatibility by using existing assets path logic if the env variable isn't set?

Ideally I'd run `ssbak save...` in the root of `/releases/{releaseTimestamp}`, with `<absPath>/project-dir/shared/assets` as the value of a `SSBAK_ASSETS_PATH` var or similar in the dotenv. And `ssbak load...` would restore to the same path.

For clarity: 

```
/project-dir
/project-dir/releases

/project-dir/releases/{timestampOfRelease}
/project-dir/releases/{timestampOfRelease}/.env  <-- symlink to shared/.env
/project-dir/releases/{timestampOfRelease}/public/assets  <-- symlink to shared/assets

/project-dir/current   <-- symlink to latest releases/release

/project-dir/shared
/project-dir/shared/.env
/project-dir/shared/assets
```

I'd happily submit a PR for it but unfort as it's Go I'm a bit out of my wheelhouse.

**Comment by axllent** [comment]
Hi @dizzystuff, thanks for the feedback. Ironically symlinks was something I considered right in the beginning, and, because we don't use symlinking here, forgot all about it! I have just made a few changes and released a beta version which you can download [here](https://github.com/axllent/ssbak/releases/tag/0.1.4-beta). 

Note that although ssbak should follow symbolic links for both the `.env` as well as the `public/assets`, it will not take these into consideration when restoring (`ssbak load ...`). This means that although `public/assets` may have been a link to elsewhere when backing up, when you restore then `public/assets` becomes a folder as the original symlink is initially renamed and then deleted (just link in this case, not the path it resolves to). This was handled in this way to remain compatible with the original sspak. You can of course manually extract just the assets with `ssbak extract ...`, so there is a workaround if you needed to restore. I could add some additional flags to specify a restore path, however at this stage I'd rather not (unless required) as it deviates from the original sspak functionality.

Please be so kind as to test it and confirm this works for you?

**Comment by dizzystuff** [comment]
@axllent I really appreciate the quick response. Have tested the beta with both `ssbak save` and `ssbak load`, and it's working as described. Thanks a tonne!

While an extra flag to specify a restore path really would be perfect, I understand the hesitation re deviating from sspak. I'm fairly confident I can handle what I need to do with `ssbak extract`.

Cheers

**Comment by axllent** [comment]
@dizzystuff Awesome, you are very welcome, and thank you for the report & testing.

I have released a "stable" version with those changes (pretty much what you are running now). If you find yourself really requiring the restore path in your deployment process, then feel free to open another issue. As I said before, I'd rather not add functionality that isn't widely used when there is a potential workaround, however I have already deviated somewhat from the original by adding in `save --ignore-resampled`, so other features/flags are always an option too (provided the core commands continue to work as expected and there is an actual use-case requirement for additional features).
